 
INSERT INTO credentials(username,password,enabled) VALUES ('guest','$2a$10$o0.vlDPfuo1hnLiplmTGU.dpvjXR3hDgMEfFhZGxn84W6FePYXCb6', TRUE);
INSERT INTO credentials(username,password,enabled) VALUES ('admin','$2a$10$8z06WZd8Z56VtXhkkX7KnOHz3XrZ7T81EfEGZ.4xDkiABH75MU/8G', TRUE);

INSERT INTO authority (username, authority, userid) VALUES ('guest', 'ROLE_USER', 1);
INSERT INTO authority (username, authority, userid) VALUES ('admin', 'ROLE_ADMIN', 2);


INSERT INTO Product (id, category, manufacturer, description, name, price, qty, status) values (1, 'Battery', 'AmazonBasics', 'Pack of 12 C Cell Alkaline Batteries 3-year shelf life so you can store for emergencies or use immediately', 'AmazonBasics C Cell Everyday Alkaline Batteries (12-Pack)', 10.59, 1000, 'active');
INSERT INTO Product (id, category, manufacturer, description, name, price, qty, status) values (2, 'Battery', 'AmazonBasics', 'Pack of 12 C Cell Alkaline Batteries 3-year shelf life so you can store for emergencies or use immediately', 'AmazonBasics C Cell Everyday Alkaline Batteries (12-Pack)', 10.59, 1000, 'active');
INSERT INTO Product (id, category, manufacturer, description, name, price, qty, status) values (3, 'Battery', 'EBL', 'EBL 2 Pack High Volume 600mAh 9V 6F22 Lithium-ion Rechargeable Battery with Universal Battery Charger', 'EBL 2 Pack High Volume 600mAh 9V 6F22 Lithium-ion Rechargeable Battery with Universal Battery Charger', 15.59, 1000, 'active');
INSERT INTO Product (id, category, manufacturer, description, name, price, qty, status) values (4, 'Battery', 'Bonai', 'Pack of 4 9V 600mAh Li-ion rechargeable batteries, Bonai batteries can be recharged up to 1200 times when fully or partially drained', 'Bonai 9V 6F22 Rechargeable Batteries 600mAh Ultra-Efficient Lithium-ion Batteries, 4 Pack', 10.59, 1000, 'active');
INSERT INTO Product (id, category, manufacturer, description, name, price, qty, status) values (5, 'Battery', 'AmazonBasics', 'Pack of 8 AA high-capacity rechargeable batteries Maintains 65% of original charge after being stored for 3 years', 'AmazonBasics AA High-Capacity Rechargeable Batteries (8-Pack) Pre-charged - Packaging May Vary', 17.59, 1000, 'active');
INSERT INTO Product (id, category, manufacturer, description, name, price, qty, status) values (6, 'Battery', 'MJKAA', 'CHOOSE RECHARGEABLE - MJKAA AA Rechargeable Batteries Can Be Used and Recharged 1000 Times Over CHOOSE LOW SELF-DISCHARGE', 'MJKAA AA Rechargeable Battery High Performance 1.2V Ni-MH AA Batteries (10 Pack)', 14.59, 1000, 'active');
INSERT INTO Product (id, category, manufacturer, description, name, price, qty, status) values (7, 'Book', 'Gayle Laakmann McDowell', 'I am not a recruiter. I am a software engineer. And as such, I know what it\'s like to be asked to whip up brilliant algorithms on the spot and then write flawless code on a whiteboard.', 'Cracking the Coding Interview: 189 Programming Questions and Solutions 6th Edition', 37.95, 250, 'active');
INSERT INTO Product (id, category, manufacturer, description, name, price, qty, status) values (8, 'Book', 'Adnan Aziz, Tsung-Hsien Lee, Amit Prakash', 'This is a larger-format version of Elements of Programming Interviews in Java. Specifically, the font size is larger, and the page size is 7"x10"', 'Elements of Programming Interviews in Java: The Insiders'' Guide', 29.96, 500, 'active'); 
INSERT INTO Product (id, category, manufacturer, description, name, price, qty, status) values (9, 'Book', 'Stuart Broad', 'It is a fact that you’ll be bombarded with system design interview questions which have become part and parcel of all the software engineering hiring processes. ', 'System Design Interview: An In-depth Overview for System Designers (A Beginner''s Guide)', 14.38, 1000, 'active');
